# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import slurm_pilot_pb2 as slurm__pilot__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in slurm_pilot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorkerProcess = channel.unary_unary(
                '/Coordinator/RegisterWorkerProcess',
                request_serializer=slurm__pilot__pb2.WorkerProcessID.SerializeToString,
                response_deserializer=slurm__pilot__pb2.Empty.FromString,
                _registered_method=True)
        self.UnregisterWorkerProcess = channel.unary_unary(
                '/Coordinator/UnregisterWorkerProcess',
                request_serializer=slurm__pilot__pb2.WorkerProcessID.SerializeToString,
                response_deserializer=slurm__pilot__pb2.Empty.FromString,
                _registered_method=True)
        self.GetNextTask = channel.unary_unary(
                '/Coordinator/GetNextTask',
                request_serializer=slurm__pilot__pb2.WorkerProcessID.SerializeToString,
                response_deserializer=slurm__pilot__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.SetTaskResult = channel.unary_unary(
                '/Coordinator/SetTaskResult',
                request_serializer=slurm__pilot__pb2.TaskResult.SerializeToString,
                response_deserializer=slurm__pilot__pb2.Empty.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorkerProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWorkerProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorkerProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkerProcess,
                    request_deserializer=slurm__pilot__pb2.WorkerProcessID.FromString,
                    response_serializer=slurm__pilot__pb2.Empty.SerializeToString,
            ),
            'UnregisterWorkerProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWorkerProcess,
                    request_deserializer=slurm__pilot__pb2.WorkerProcessID.FromString,
                    response_serializer=slurm__pilot__pb2.Empty.SerializeToString,
            ),
            'GetNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTask,
                    request_deserializer=slurm__pilot__pb2.WorkerProcessID.FromString,
                    response_serializer=slurm__pilot__pb2.TaskAssignment.SerializeToString,
            ),
            'SetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTaskResult,
                    request_deserializer=slurm__pilot__pb2.TaskResult.FromString,
                    response_serializer=slurm__pilot__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorkerProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/RegisterWorkerProcess',
            slurm__pilot__pb2.WorkerProcessID.SerializeToString,
            slurm__pilot__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterWorkerProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/UnregisterWorkerProcess',
            slurm__pilot__pb2.WorkerProcessID.SerializeToString,
            slurm__pilot__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/GetNextTask',
            slurm__pilot__pb2.WorkerProcessID.SerializeToString,
            slurm__pilot__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/SetTaskResult',
            slurm__pilot__pb2.TaskResult.SerializeToString,
            slurm__pilot__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
