# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slurm_pilot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slurm_pilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11slurm_pilot.proto\"\x07\n\x05\x45mpty\"b\n\x0fWorkerProcessID\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cslurm_job_id\x18\x03 \x01(\x03\x12\x10\n\x08hostname\x18\x04 \x01(\t\x12\x0b\n\x03pid\x18\x05 \x01(\x03\"K\n\x08TaskDefn\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x66unction\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\x12\x0e\n\x06kwargs\x18\x04 \x01(\x0c\"T\n\x0eTaskAssignment\x12\x11\n\texit_flag\x18\x01 \x01(\x08\x12\x16\n\x0etask_available\x18\x02 \x01(\x08\x12\x17\n\x04task\x18\x03 \x01(\x0b\x32\t.TaskDefn\"\x9c\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0ctask_success\x18\x02 \x01(\x08\x12\x0f\n\x07return_\x18\x03 \x01(\x0c\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x10\n\x08\x65rror_id\x18\x05 \x01(\t\x12$\n\nprocess_id\x18\x06 \x01(\x0b\x32\x10.WorkerProcessID\x12\x0f\n\x07runtime\x18\x07 \x01(\x01\x32\xd5\x01\n\x0b\x43oordinator\x12\x33\n\x15RegisterWorkerProcess\x12\x10.WorkerProcessID\x1a\x06.Empty\"\x00\x12\x35\n\x17UnregisterWorkerProcess\x12\x10.WorkerProcessID\x1a\x06.Empty\"\x00\x12\x32\n\x0bGetNextTask\x12\x10.WorkerProcessID\x1a\x0f.TaskAssignment\"\x00\x12&\n\rSetTaskResult\x12\x0b.TaskResult\x1a\x06.Empty\"\x00\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slurm_pilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=21
  _globals['_EMPTY']._serialized_end=28
  _globals['_WORKERPROCESSID']._serialized_start=30
  _globals['_WORKERPROCESSID']._serialized_end=128
  _globals['_TASKDEFN']._serialized_start=130
  _globals['_TASKDEFN']._serialized_end=205
  _globals['_TASKASSIGNMENT']._serialized_start=207
  _globals['_TASKASSIGNMENT']._serialized_end=291
  _globals['_TASKRESULT']._serialized_start=294
  _globals['_TASKRESULT']._serialized_end=450
  _globals['_COORDINATOR']._serialized_start=453
  _globals['_COORDINATOR']._serialized_end=666
# @@protoc_insertion_point(module_scope)
